# Generated by Django 4.0.3 on 2022-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10)),
                ('proffesor_id', models.CharField(max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.ManyToManyField(to='Ranker.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('professors', models.ManyToManyField(to='Ranker.professor')),
            ],
        ),
    ]
