# Generated by Django 4.0.3 on 2022-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
