# Generated by Django 4.0.3 on 2022-03-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ranker', '0002_rating_semester_rating_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='proffesor_id',
            new_name='profesor_id',
        ),
    ]
